### ISSUE TITLE
Replace PS with PowerShell in README

### ISSUE THREAD

**Issue by RoxKilly** [claustromaniac/Compare-UserJS#5]
Nice work; thanks for sharing it with us.

In the readme, the first time you mention powershell is in this sentence:

> This script requires only PS v2+, which comes pre-installed on Windows 7

Many who arrive here without context of what this tool is and start with the readme will not know what PS refers to.   It only made sense by inference when you mentioned PowerShell a couple of times later on in the document.  I suggest you replace PS with PowerShell, assuming that's what you meant.

**Comment by claustromaniac** [comment]
I think I used PS there because I used PowerShell in the short description above, but who reads those anyway. I'll change it, thanks.

I'm sure I could still improve the readme, though. I didn't want it to sound professional because I'm _not_ professional, but maybe I overdid that a bit. :sweat_smile:
